name: Web E2E Tests

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Node version setup
      run: node --version

    - name: Install dependencies
      run: npm install

    - name: Cypress run
      run: npx cypress run