name: Web E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        headless: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-reports
        path: |
          cypress/reports
          cypress/screenshots
          cypress/videos
        retention-days: 30
        if-no-files-found: warn

    - name: Deploy test report
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: cypress/reports/html
        publish_branch: gh-pages
        keep_files: true