name: Web E2E Tests

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Node version setup
      run: node --version

    - name: Install dependencies
      run: npm install

    - name: E2E Tests run
      run: npx cypress run

    - name: Generate E2E Test Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }} 
      with:
        name: reports
        path: |
          cypress/videos
          cypress/screenshots
          cypress/reports