name: Web E2E Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Node version setup
      run: node --version

    - name: Install dependencies
      run: npm install

    - name: E2E Tests run
      run: npx cypress run --spec "cypress/e2e/drag-and-drop-and-windows.cy.js"
      continue-on-error: true

    - name: Generate report files
      run: |
        npm run generate-report
        npm run zip-report

    - name: Download ao report
      run: |
        echo '<p style="text-align:center;margin-top:20px;">
        <a href="report.zip" download style="background:#0078D4;color:#fff;padding:10px 20px;border-radius:8px;text-decoration:none;">⬇️ Baixar Relatório</a>
        </p>' >> report/index.html

    - name: Publish in GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./report