name: Web E2E Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Node version setup
      run: node --version

    - name: Install dependencies
      run: npm install

    - name: Create reports directory
      run: |
        mkdir -p cypress/reports
        mkdir -p cypress/screenshots
        mkdir -p cypress/videos

    - name: E2E Tests run
      run: npx cypress run --spec "cypress/e2e/trabalho-final.cy.js"

    - name: Generate E2E Test Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }} 
      with:
        name: reports
        path: cypress/reports
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false

    - name: Publish in GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}