name: Web E2E Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Node version setup
      run: node --version

    - name: Install dependencies
      run: npm install

    - name: Create reports directory
      run: |
        mkdir -p cypress/reports/json
        mkdir -p cypress/reports/html

    - name: E2E Tests run
      run: |
        npx cypress run --spec "cypress/e2e/drag-and-drop-and-windows.cy.js" \
        --reporter cypress-multi-reporters \
        --reporter-options configFile=reporter-config.json
      continue-on-error: true

    - name: Generate merged report
      if: always()
      run: |
        npx mochawesome-merge cypress/reports/json/*.json > cypress/reports/mochawesome-final.json
        npx marge cypress/reports/mochawesome-final.json --reportDir cypress/reports/html --inline

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }} 
      with:
        name: reports
        path: |
          cypress/videos
          cypress/screenshots
          cypress/reports

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Cypress Tests
        path: cypress/reports/mochawesome-final.json
        reporter: mocha-json