name: Web E2E Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Node version setup
      run: node --version

    - name: Install dependencies
      run: npm install

    - name: Create reports directory
      run: |
        mkdir -p cypress/reports
        mkdir -p cypress/screenshots
        mkdir -p cypress/videos

    - name: E2E Tests run
      run: npx cypress run --spec "cypress/e2e/drag-and-drop-and-windows.cy.js"

    - name: Generate E2E Test Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }} 
      with:
        name: reports
        path: cypress/reports
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false

    - name: Prepare HTML Report
      if: always()
      run: |
        if [ -d "cypress/reports" ]; then
          cd cypress/reports
          zip -r report.zip .
          echo '<p style="text-align:center;margin-top:20px;">
          <a href="report.zip" download style="background:#0078D4;color:#fff;padding:10px 20px;border-radius:8px;text-decoration:none;">⬇️ Baixar Relatório Completo</a>
          </p>' >> index.html
        fi

    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cypress/reports
        enable_jekyll: false
        keep_files: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'docs: update test reports'